app:
  name: "web_app"
  mode: "dev"
  prot: 8081

log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: localhost
  port: 3306
  user: "root"
  password: "root"
  dbname: "test"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: ""
  port:
  password: ""
  db: 0
  pool_size: 100